name: Build

on: [push, pull_request]

env:
  # CIBW_BUILD_VERBOSITY: 1
  # CIBW_TEST_REQUIRES: pytest
  CIBW_TEST_COMMAND: python -c "import sys, pyfastnoisesimd; sys.exit(0 if pyfastnoisesimd.test().wasSuccessful() else 1)"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        name: Install Python
        with:
          python-version: '3.10'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels for CPython 3.8
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp38-*"
          CIBW_BEFORE_BUILD: pip install setuptools oldest-supported-numpy

      - name: Build wheels for CPython 3.9
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp39-*"
          CIBW_BEFORE_BUILD: pip install setuptools oldest-supported-numpy

      - name: Build wheels for CPython 3.10
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp310-*"
          CIBW_BEFORE_BUILD: pip install setuptools oldest-supported-numpy

      - name: Build wheels for CPython 3.11
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp311-*"
          CIBW_BEFORE_BUILD: pip install setuptools oldest-supported-numpy

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl